name: Build and deploy Python app to Azure Web App - projectwebapp

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  PYTHON_VERSION: '3.10'
  AZURE_WEBAPP_NAME: 'projectwebapp'  # Define as env variable but use directly in steps

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      actions: read
      packages: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Debug Python version
        run: echo "Using Python ${{ env.PYTHON_VERSION }}"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'

      - name: Create virtual environment
        run: |
          python -m venv venv
          echo "VENV_PATH=$PWD/venv" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          source $VENV_PATH/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          pip list  # Debug installed packages

      - name: Run basic sanity check
        run: |
          source $VENV_PATH/bin/activate
          python -c "import sys; print(f'Python {sys.version}')"
          [ -f requirements.txt ] && echo "requirements.txt exists" || echo "requirements.txt missing"

      - name: Create deployment package
        run: |
          zip -r release.zip . -x 'venv/*' '.*' '__pycache__/*' '*.git*'
          ls -lh release.zip  # Show package size

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip
          retention-days: 1

  deploy:
    runs-on: ubuntu-22.04
    needs: build
    environment: 
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Show deployment files
        run: |
          ls -la
          unzip -l release.zip | head -20  # Show first 20 files in zip

      - name: Login to Azure
        uses: azure/login@v2.1.0
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}
        continue-on-error: false

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3.1.0
        id: deploy-to-webapp
        with:
          app-name: 'projectwebapp'  # Using hardcoded value
          slot-name: 'Production'    # Using hardcoded value
          package: release.zip
