name: Build and deploy Python app to Azure Web App - projectwebapp

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  PYTHON_VERSION: '3.10'

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 15
    permissions:
      contents: read
      actions: read
      packages: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Clear GitHub Actions cache
        run: |
          sudo rm -rf /opt/hostedtoolcache/Python/
          sudo rm -rf /usr/local/lib/python*
          echo "Cache cleared"

      - name: Setup Python (with retry)
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'

      - name: Verify Python installation
        run: |
          python --version
          which python
          pip --version

      - name: Create virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
          echo "VIRTUAL_ENV=$PWD/venv" >> $GITHUB_ENV
          echo "$PWD/venv/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip list

      - name: Create deployment package
        run: |
          zip -r release.zip . -x 'venv/*' '.*' '__pycache__/*' '*.git*'
          ls -lh release.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip
          retention-days: 1

  deploy:
    runs-on: ubuntu-22.04
    needs: build
    environment: 
      name: 'Production'
    
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'projectwebapp'
          slot-name: 'Production'
          package: release.zip
