name: Build and deploy Python app to Azure Web App - projectwebapp

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  PYTHON_VERSION: '3.10'
  AZURE_WEBAPP_NAME: 'projectwebapp'
  AZURE_WEBAPP_SLOT: 'Production'

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      actions: read
      packages: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'

      - name: Create and activate virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
          echo "VIRTUAL_ENV=$PWD/venv" >> $GITHUB_ENV
          echo "$PWD/venv/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests (optional)
        run: |
          # Add your test commands here if needed
          # Example: pytest tests/

      - name: Create deployment package
        run: |
          # Exclude virtual environment from deployment
          zip -r release.zip . -x 'venv/*' '.*' '__pycache__/*'

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-22.04
    needs: build
    environment:
      name: ${{ env.AZURE_WEBAPP_SLOT }}
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    permissions:
      id-token: write
      contents: read
      actions: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Login to Azure
        uses: azure/login@v2.1.0
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_4EDFC51FBF484524A5A40DE0E0EAC301 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_30CA79F3402547789A16AAE45CEC2940 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_2BF2CEA73E3D4614A02B496006CE6F59 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3.1.0
        id: deploy-to-webapp
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: ${{ env.AZURE_WEBAPP_SLOT }}
          package: release.zip
